### ISSUE TITLE
Promise.any should throw AggregateError instead of array of exceptions

### ISSUE THREAD

**Issue by chicoxyzzy** [es-shims/Promise.any#1]
Current implementation doesn't match latest spec text and returns array of exceptions instead of `AggregateError`. @ljharb should we create new repo and package for `AggregateError`?

**Comment by ljharb** [comment]
Whoops, thanks, totally spaced on that. No, i think we don’t need to do that - we can add it here. I’ll do that tomorrow.

**Comment by ljharb** [comment]
Waiting on some spec review questions first.

**Comment by ljharb** [comment]
Ended up making https://npmjs.com/es-aggregate-error.
