### ISSUE TITLE
triggerUncaughtException error for rejected promises

### ISSUE THREAD

**Issue by ghost** [es-shims/Promise.any#12]
Hello,

I don't know why but the console output of node.js returns triggerUncaughtException, while executing multiple POST requests using axios library

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 400".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Could we silence this rejection?

**Comment by ljharb** [comment]
What version of node are you seeing this in? Does the same thing happen in a version of node with a native Promise.any?

**Comment by ayanamidev** [comment]
@ljharb I am using the LTS version of the node.js, looks like it happens for the built-in Promise.any?

**Comment by ayanamidev** [comment]
I think it would be appropriate to create an issue here instead https://github.com/nodejs/node/issues, thanks!

**Comment by ljharb** [comment]
If it happens for the builtin one then it’s likely behaving by spec - node just uses v8’ s, which is in chrome.
